version: "3.9"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=reactor
      - DOCKER_INFLUXDB_INIT_PASSWORD=growgrow
      - DOCKER_INFLUXDB_INIT_ORG=trendbit
      - DOCKER_INFLUXDB_INIT_BUCKET=smpbr
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
      - INFLUXDB_REPORTING_DISABLED=true
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - ./influxdb:/etc/influxdb2
    networks:
      - smpbr-influx
    ports:
      - 8086:8086

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    environment:
      - LOG_LEVEL=INFO
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ORG=trendbit
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - KAPACITOR_URL=http://kapacitor:9092
    networks:
      - smpbr-influx
    depends_on:
      - influxdb
    ports:
      - 8888:8888
    volumes:
       - chronograf-data:/var/lib/chronograf

  kapacitor:
    image: kapacitor:latest
    container_name: kapacitor
    environment:
      - KAPACITOR_LOGGING_LEVEL=INFO
      - KAPACITOR_REPORTING_ENABLED=false
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_INFLUXDB_0_USERNAME=trendbit
      - KAPACITOR_INFLUXDB_0_PASSWORD=my-super-secret-auth-token
      - KAPACITOR_INFLUXDB_0_DISABLE_SUBSCRIPTIONS=true
    networks:
      - smpbr-influx
    depends_on:
      - influxdb
    ports:
      - 9092:9092

  smpbr_data_mdns:
    image: ydkn/avahi:latest
    network_mode: host
    container_name: smpbr_data_mdns
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    volumes:
      - ./avahi/services:/etc/avahi/services
      - ./avahi/avahi-daemon.conf:/etc/avahi/avahi-daemon.conf

volumes:
  influxdb-data:
  chronograf-data:

networks:
  smpbr-influx:
